# Generated by Django 3.2.15 on 2022-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.TextField()),
                ('user_name', models.TextField()),
                ('password', models.TextField()),
                ('dsn', models.TextField()),
                ('port', models.TextField()),
            ],
        ),
    ]
