# Generated by Django 3.2.15 on 2022-09-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20220929_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField()),
                ('db_type', models.TextField()),
                ('insert_type', models.TextField()),
                ('query', models.TextField()),
            ],
        ),
    ]
