# Generated by Django 3.2.15 on 2022-09-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
