# Generated by Django 3.2.15 on 2022-09-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_set',
            name='db_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('sql', 'SQL')], default='oracle', max_length=6),
        ),
        migrations.AlterField(
            model_name='query_set',
            name='insert_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=10),
        ),
    ]
