# Generated by Django 3.2.15 on 2022-09-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20220930_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congif',
            name='db_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('sql', 'SQL')], default='oracle', max_length=6),
        ),
    ]
